spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://81.68.241.238:3306/xxb
      username: root
      password: 123456
    url: jdbc:mysql://81.68.241.238:3306/mybatis
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true