spring:
  datasource:
    url: jdbc:mysql://81.68.241.238:3306/mybatis
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver