spring:
  datasource:
    url: jdbc:mysql://81.68.241.238:3306/qlExpress
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl